### ISSUE TITLE
Rebinding "Reset Look" key bug

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#114]
How to reproduce:
1. Open controller settings.
2. Try to change "Reset Look" key (from LS to RS or otherwise).
3. A new ghost (and untitled) key will be displayed, as you can see on the screenshot:
http://veg.by/z/2016-07-13-20-27-12-a8ccb320.png

UPD. It seems that the ghost item have to be "First Person View" key, but for some reason it is hidden when I'm opening controller settings before starting gameplay. If I open controller settings in pause menu, this key is visible.

**Comment by flibitijibibo** [comment]
Fixed in the next build.

**Comment by vrubleg** [comment]
I have this item in the changelog:

```
12/08 - Fixed "ghost" first-person view option in controls
```

But it seems, that the problem is not fixed. "First Person View" still not displayed when controls settings are opened before the gameplay, and "ghost" key still appears when I'm changing "Reset Look" from the LS to RS or otherwise.

I see that this bug occurs only when I'm choosing my 200% progress slot. When I choose other slots (less than 100% progress), this key also is invisible and "ghost" key isn't shown after changing "Reset Look".

**Comment by vrubleg** [comment]
In a nutshell. The "First Person View" key isn't displayed in controls before gameplay where it have to be displayed (more than 100% progress). But when you try to assign LS or RS to the "Reset Look", the "ghost" key will appear.

**Comment by flibitijibibo** [comment]
Got it for real this time. Instead of hiding it we now just call the binding "???" when not unlocked, which turns out to be a lot easier and is a nice little tease for the future.

**Comment by vrubleg** [comment]
I like the first idea with a hidden key more. "???" key is a bit confusing. I'd rather think that "???" is a missing string. IMHO :)

**Comment by flibitijibibo** [comment]
Had a second look, turns out my implementation allowed for that... a lot less Suffix variables to modify too. So yeah, next build will keep it hidden.

**Comment by vrubleg** [comment]
There is still some small glitch. Look at the First Person View right after opening of the controls menu:
https://www.youtube.com/watch?v=GkCQ2tYEN3c (key value is displayed on the next line for a second, just after opening of the controls settings).

It is not significant, but looks weird a little bit.

**Comment by flibitijibibo** [comment]
Yeah, that's a nasty consequence of how panels are rendered between transitions. From what I can tell it's a bug that persists across various menus, including the keyboard menu (if the bound key graphic is wide enough). It's a pretty old bug, not sure if there's much we can do aside from ignoring the line wrapping logic in very specific cases.
