### ISSUE TITLE
Scaling Mode doesn't affect gameplay just after changing

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#121]
How to reproduce:
1. Start the game, start gameplay.
2. Open settings, change the Scaling Mode to Pixel-Perfect. You will see that scaling mode of the menu is changed.
3. Return to the gameplay. You will see that scaling mode of the gameplay isn't changed.
4. Open settings, change resolution to something else, apply, change resolution to the previous value, apply.
5. Return to the gameplay. You will see that scaling mode is changed for gameplay also.

**Comment by flibitijibibo** [comment]
Fixed in the next build, was bad timing when querying view scale.

**Comment by vrubleg** [comment]
It is still buggy in the [latest build](https://steamdb.info/app/224760/history/?changeid=2127921).

**Comment by flibitijibibo** [comment]
The scale fix won't be there until later tonight, the current build for Windows is from last night.

**Comment by renaudbedard** [comment]
Correct; for the record, Ethan makes linux and macOS builds, I make Windows builds,... and I can't make Windows builds during the day. :)
