### ISSUE TITLE
Supersampled + Windowed mode

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#124]
The latest version has this change:

> 26/07 - Supersampling screen mode only supported in fullscreen because it depends on FNA's faux-backbuffer, which only enables itself in actual fullscreen mode

But sometimes supersampled is still available in windowed modes, and it works like this:
http://veg.by/z/2016-07-27-07-08-00-a7e301ed.png

Try to change the Screen Mode and Scaling Mode settings randomly to reproduce it.

**Comment by vrubleg** [comment]
It seems that supersampled is available when windowed mode was chosen using the left key, and it is not available when windowed mode was chosen using the right key. That's fun :)

**Comment by renaudbedard** [comment]
Ahaha wow, quality software. I'll look into that, sorry!

**Comment by flibitijibibo** [comment]
This is fixed in the next update - we can have supersampled window mode, I just happened to make both a bug in FEZ and a bug in FNA!

The window size problem was the result of improved GraphicsDeviceManager.ApplyChanges() timing accuracy fixes...

https://github.com/FNA-XNA/FNA/commit/5bb6b6deee2e37c95be6803666549bf0ac13a61b

... so my original code to do a re-reset for a large backbuffer caused the window size to get changed to the supersample value and not the intended window size. That was an easy fix in FEZ, but then it turns out my attempt to remove FNAPlatform calls in the GLDevice implementations had actually stripped out FNA's ability to use faux-backbuffers in windowed modes, so I got to reintroduce that...

https://github.com/FNA-XNA/FNA/commit/6b772a5d7c91cf9bc8c48fed41b91902f8236c7d

With both a FEZ update and an FNA update this should be fixed. Supersampling for everybody!

**Comment by renaudbedard** [comment]
Oh! Even better :D

**Comment by renaudbedard** [comment]
Looks like there's still an issue with supersampling, but it might be unrelated.

![menubug](https://cloud.githubusercontent.com/assets/251134/17200034/d7bb0a7c-544f-11e6-8de2-0b6ea6a1077f.gif)

Steps : start with a resolution in which supersampling is the same as full aspect, switch to supersampling, then move to a resolution where supersampling has an effect.

@flibitijibibo : Can you take a look when you have a sec?

**Comment by flibitijibibo** [comment]
Looks like it's rendering the highlighter in the center based on the new resolution, but positioning and scaling based on the old size. I would expect that in Dynamic mode, but not static... Guess we have to find out why the highlighter doesn't seem to know about the new target sizes.

**Comment by renaudbedard** [comment]
Actually the whole menu system is borked after this point, here's the upper level...

![image](https://cloud.githubusercontent.com/assets/251134/17200123/8a639612-5450-11e6-864d-c7dc1ab7a18d.png)

Most likely the viewscale isn't getting propagated correctly. Closing the pause menu and reopening fixes it.

**Comment by flibitijibibo** [comment]
Ah, yeah, this may be a wider problem then. In a commit from the last few days I made that fix to the scale mode viewScale read, we should probably lighten up on the scale caching when we do that in a static variable anyway.

**Comment by flibitijibibo** [comment]
Actually, maybe we should add an OnViewScaleChanged func... That was what I would have liked for my other fix.

**Comment by flibitijibibo** [comment]
This was actually my fault again:

https://github.com/FNA-XNA/FNA/commit/8c8e91679811502c7e9fa97d13915b8ef2251d55
